receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
exporters:
  debug:
    verbosity: detailed
  azuremonitor:
    connection_string: "<app insights connection string from azure portal>"
service:
  pipelines:
    logs:
      receivers: [ otlp ]
      exporters: [ azuremonitor ]
    traces:
      receivers: [ otlp ]
      exporters: [ azuremonitor ]